export interface VoterContact {
  firstName: string;
  lastName: string;
  team: string;
  date: string;
  tactic: string;
  attempts: number;
  contacts: number;
  notHome: number;
  refusal: number;
  badData: number;
  support: number;
  oppose: number;
  undecided: number;
}

export interface QueryParams {
  tactic: string;
  resultType: string;
  person: string;
  date: string;
}

export const TEST_DATA: VoterContact[] = [
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-01",
    tactic: "Phone",
    attempts: 17,
    contacts: 10,
    notHome: 0,
    refusal: 6,
    badData: 1,
    support: 4,
    oppose: 3,
    undecided: 3
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-01",
    tactic: "SMS",
    attempts: 17,
    contacts: 11,
    notHome: 3,
    refusal: 3,
    badData: 0,
    support: 8,
    oppose: 3,
    undecided: 0
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-01",
    tactic: "Canvas",
    attempts: 8,
    contacts: 6,
    notHome: 0,
    refusal: 2,
    badData: 0,
    support: 6,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-01",
    tactic: "SMS",
    attempts: 19,
    contacts: 13,
    notHome: 6,
    refusal: 0,
    badData: 0,
    support: 8,
    oppose: 3,
    undecided: 2
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-01",
    tactic: "SMS",
    attempts: 15,
    contacts: 5,
    notHome: 3,
    refusal: 0,
    badData: 7,
    support: 3,
    oppose: 2,
    undecided: 0
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-02",
    tactic: "SMS",
    attempts: 6,
    contacts: 1,
    notHome: 5,
    refusal: 0,
    badData: 0,
    support: 1,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-02",
    tactic: "Phone",
    attempts: 7,
    contacts: 6,
    notHome: 1,
    refusal: 0,
    badData: 0,
    support: 4,
    oppose: 0,
    undecided: 2
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-02",
    tactic: "SMS",
    attempts: 13,
    contacts: 8,
    notHome: 1,
    refusal: 1,
    badData: 3,
    support: 7,
    oppose: 1,
    undecided: 0
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-02",
    tactic: "Phone",
    attempts: 18,
    contacts: 2,
    notHome: 3,
    refusal: 5,
    badData: 8,
    support: 0,
    oppose: 2,
    undecided: 0
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-02",
    tactic: "SMS",
    attempts: 12,
    contacts: 2,
    notHome: 3,
    refusal: 3,
    badData: 4,
    support: 0,
    oppose: 1,
    undecided: 1
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-03",
    tactic: "Canvas",
    attempts: 7,
    contacts: 3,
    notHome: 1,
    refusal: 0,
    badData: 3,
    support: 3,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-03",
    tactic: "SMS",
    attempts: 10,
    contacts: 7,
    notHome: 2,
    refusal: 1,
    badData: 0,
    support: 4,
    oppose: 3,
    undecided: 0
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-03",
    tactic: "SMS",
    attempts: 16,
    contacts: 3,
    notHome: 5,
    refusal: 8,
    badData: 0,
    support: 1,
    oppose: 2,
    undecided: 0
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-03",
    tactic: "Phone",
    attempts: 14,
    contacts: 12,
    notHome: 2,
    refusal: 0,
    badData: 0,
    support: 5,
    oppose: 1,
    undecided: 6
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-03",
    tactic: "Phone",
    attempts: 19,
    contacts: 3,
    notHome: 13,
    refusal: 3,
    badData: 0,
    support: 2,
    oppose: 0,
    undecided: 1
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-04",
    tactic: "SMS",
    attempts: 18,
    contacts: 17,
    notHome: 1,
    refusal: 0,
    badData: 0,
    support: 9,
    oppose: 3,
    undecided: 5
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-04",
    tactic: "Phone",
    attempts: 10,
    contacts: 4,
    notHome: 2,
    refusal: 1,
    badData: 3,
    support: 1,
    oppose: 2,
    undecided: 1
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-04",
    tactic: "Canvas",
    attempts: 15,
    contacts: 11,
    notHome: 1,
    refusal: 1,
    badData: 2,
    support: 1,
    oppose: 8,
    undecided: 2
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-04",
    tactic: "SMS",
    attempts: 9,
    contacts: 1,
    notHome: 4,
    refusal: 3,
    badData: 1,
    support: 1,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-04",
    tactic: "Phone",
    attempts: 14,
    contacts: 1,
    notHome: 4,
    refusal: 0,
    badData: 9,
    support: 0,
    oppose: 1,
    undecided: 0
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-05",
    tactic: "Canvas",
    attempts: 9,
    contacts: 5,
    notHome: 2,
    refusal: 2,
    badData: 0,
    support: 4,
    oppose: 0,
    undecided: 1
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-05",
    tactic: "Canvas",
    attempts: 8,
    contacts: 6,
    notHome: 1,
    refusal: 0,
    badData: 1,
    support: 2,
    oppose: 0,
    undecided: 4
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-05",
    tactic: "Phone",
    attempts: 10,
    contacts: 8,
    notHome: 2,
    refusal: 0,
    badData: 0,
    support: 8,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-05",
    tactic: "Phone",
    attempts: 8,
    contacts: 7,
    notHome: 1,
    refusal: 0,
    badData: 0,
    support: 6,
    oppose: 0,
    undecided: 1
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-05",
    tactic: "Phone",
    attempts: 7,
    contacts: 2,
    notHome: 2,
    refusal: 1,
    badData: 2,
    support: 0,
    oppose: 2,
    undecided: 0
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-06",
    tactic: "Phone",
    attempts: 11,
    contacts: 6,
    notHome: 4,
    refusal: 0,
    badData: 1,
    support: 3,
    oppose: 3,
    undecided: 0
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-06",
    tactic: "Canvas",
    attempts: 16,
    contacts: 7,
    notHome: 2,
    refusal: 7,
    badData: 0,
    support: 0,
    oppose: 0,
    undecided: 7
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-06",
    tactic: "SMS",
    attempts: 17,
    contacts: 7,
    notHome: 6,
    refusal: 4,
    badData: 0,
    support: 7,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-06",
    tactic: "Phone",
    attempts: 5,
    contacts: 3,
    notHome: 2,
    refusal: 0,
    badData: 0,
    support: 1,
    oppose: 1,
    undecided: 1
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-06",
    tactic: "SMS",
    attempts: 18,
    contacts: 3,
    notHome: 0,
    refusal: 8,
    badData: 7,
    support: 2,
    oppose: 1,
    undecided: 0
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-07",
    tactic: "Phone",
    attempts: 8,
    contacts: 5,
    notHome: 1,
    refusal: 0,
    badData: 2,
    support: 2,
    oppose: 2,
    undecided: 1
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-07",
    tactic: "Phone",
    attempts: 19,
    contacts: 17,
    notHome: 1,
    refusal: 1,
    badData: 0,
    support: 4,
    oppose: 1,
    undecided: 12
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-07",
    tactic: "SMS",
    attempts: 7,
    contacts: 5,
    notHome: 2,
    refusal: 0,
    badData: 0,
    support: 4,
    oppose: 1,
    undecided: 0
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-07",
    tactic: "SMS",
    attempts: 17,
    contacts: 9,
    notHome: 3,
    refusal: 3,
    badData: 2,
    support: 2,
    oppose: 4,
    undecided: 3
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-07",
    tactic: "SMS",
    attempts: 15,
    contacts: 9,
    notHome: 6,
    refusal: 0,
    badData: 0,
    support: 2,
    oppose: 4,
    undecided: 3
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-08",
    tactic: "Canvas",
    attempts: 14,
    contacts: 2,
    notHome: 8,
    refusal: 2,
    badData: 2,
    support: 2,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-08",
    tactic: "SMS",
    attempts: 18,
    contacts: 9,
    notHome: 1,
    refusal: 3,
    badData: 5,
    support: 5,
    oppose: 2,
    undecided: 2
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-08",
    tactic: "SMS",
    attempts: 18,
    contacts: 8,
    notHome: 8,
    refusal: 1,
    badData: 1,
    support: 2,
    oppose: 0,
    undecided: 6
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-08",
    tactic: "SMS",
    attempts: 19,
    contacts: 18,
    notHome: 0,
    refusal: 0,
    badData: 1,
    support: 5,
    oppose: 2,
    undecided: 11
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-08",
    tactic: "Canvas",
    attempts: 10,
    contacts: 9,
    notHome: 1,
    refusal: 0,
    badData: 0,
    support: 7,
    oppose: 0,
    undecided: 2
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-09",
    tactic: "Canvas",
    attempts: 11,
    contacts: 6,
    notHome: 5,
    refusal: 0,
    badData: 0,
    support: 6,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-09",
    tactic: "SMS",
    attempts: 14,
    contacts: 3,
    notHome: 4,
    refusal: 0,
    badData: 7,
    support: 0,
    oppose: 2,
    undecided: 1
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-09",
    tactic: "Canvas",
    attempts: 11,
    contacts: 6,
    notHome: 4,
    refusal: 1,
    badData: 0,
    support: 2,
    oppose: 2,
    undecided: 2
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-09",
    tactic: "SMS",
    attempts: 10,
    contacts: 1,
    notHome: 0,
    refusal: 0,
    badData: 9,
    support: 1,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-09",
    tactic: "SMS",
    attempts: 10,
    contacts: 4,
    notHome: 5,
    refusal: 0,
    badData: 1,
    support: 3,
    oppose: 0,
    undecided: 1
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-10",
    tactic: "SMS",
    attempts: 13,
    contacts: 3,
    notHome: 6,
    refusal: 4,
    badData: 0,
    support: 2,
    oppose: 0,
    undecided: 1
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-10",
    tactic: "Phone",
    attempts: 7,
    contacts: 4,
    notHome: 1,
    refusal: 2,
    badData: 0,
    support: 0,
    oppose: 0,
    undecided: 4
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-10",
    tactic: "SMS",
    attempts: 11,
    contacts: 7,
    notHome: 3,
    refusal: 1,
    badData: 0,
    support: 3,
    oppose: 0,
    undecided: 4
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-10",
    tactic: "Phone",
    attempts: 12,
    contacts: 11,
    notHome: 0,
    refusal: 1,
    badData: 0,
    support: 8,
    oppose: 3,
    undecided: 0
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-10",
    tactic: "Phone",
    attempts: 9,
    contacts: 1,
    notHome: 0,
    refusal: 3,
    badData: 5,
    support: 0,
    oppose: 0,
    undecided: 1
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-11",
    tactic: "Phone",
    attempts: 17,
    contacts: 10,
    notHome: 5,
    refusal: 1,
    badData: 1,
    support: 5,
    oppose: 3,
    undecided: 2
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-11",
    tactic: "SMS",
    attempts: 8,
    contacts: 6,
    notHome: 1,
    refusal: 0,
    badData: 1,
    support: 1,
    oppose: 0,
    undecided: 5
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-11",
    tactic: "Canvas",
    attempts: 17,
    contacts: 7,
    notHome: 0,
    refusal: 3,
    badData: 7,
    support: 2,
    oppose: 2,
    undecided: 3
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-11",
    tactic: "Phone",
    attempts: 5,
    contacts: 1,
    notHome: 2,
    refusal: 0,
    badData: 2,
    support: 1,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-11",
    tactic: "Phone",
    attempts: 7,
    contacts: 4,
    notHome: 1,
    refusal: 0,
    badData: 2,
    support: 2,
    oppose: 1,
    undecided: 1
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-12",
    tactic: "Canvas",
    attempts: 5,
    contacts: 4,
    notHome: 0,
    refusal: 1,
    badData: 0,
    support: 2,
    oppose: 1,
    undecided: 1
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-12",
    tactic: "SMS",
    attempts: 7,
    contacts: 2,
    notHome: 4,
    refusal: 0,
    badData: 1,
    support: 1,
    oppose: 0,
    undecided: 1
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-12",
    tactic: "SMS",
    attempts: 13,
    contacts: 9,
    notHome: 0,
    refusal: 1,
    badData: 3,
    support: 7,
    oppose: 2,
    undecided: 0
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-12",
    tactic: "Phone",
    attempts: 18,
    contacts: 11,
    notHome: 0,
    refusal: 1,
    badData: 6,
    support: 7,
    oppose: 3,
    undecided: 1
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-12",
    tactic: "Phone",
    attempts: 18,
    contacts: 15,
    notHome: 2,
    refusal: 1,
    badData: 0,
    support: 4,
    oppose: 3,
    undecided: 8
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-13",
    tactic: "Canvas",
    attempts: 7,
    contacts: 1,
    notHome: 3,
    refusal: 3,
    badData: 0,
    support: 1,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-13",
    tactic: "SMS",
    attempts: 6,
    contacts: 4,
    notHome: 2,
    refusal: 0,
    badData: 0,
    support: 1,
    oppose: 3,
    undecided: 0
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-13",
    tactic: "SMS",
    attempts: 14,
    contacts: 7,
    notHome: 1,
    refusal: 5,
    badData: 1,
    support: 0,
    oppose: 0,
    undecided: 7
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-13",
    tactic: "SMS",
    attempts: 15,
    contacts: 11,
    notHome: 2,
    refusal: 2,
    badData: 0,
    support: 8,
    oppose: 1,
    undecided: 2
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-13",
    tactic: "SMS",
    attempts: 12,
    contacts: 5,
    notHome: 7,
    refusal: 0,
    badData: 0,
    support: 2,
    oppose: 0,
    undecided: 3
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-14",
    tactic: "Phone",
    attempts: 12,
    contacts: 4,
    notHome: 3,
    refusal: 2,
    badData: 3,
    support: 4,
    oppose: 0,
    undecided: 0
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    team: "Local Party",
    date: "2025-01-14",
    tactic: "SMS",
    attempts: 16,
    contacts: 7,
    notHome: 7,
    refusal: 2,
    badData: 0,
    support: 1,
    oppose: 5,
    undecided: 1
  },
  {
    firstName: "Alex",
    lastName: "Johnson",
    team: "Local Party",
    date: "2025-01-14",
    tactic: "Phone",
    attempts: 13,
    contacts: 12,
    notHome: 1,
    refusal: 0,
    badData: 0,
    support: 9,
    oppose: 2,
    undecided: 1
  },
  {
    firstName: "Maria",
    lastName: "Martinez",
    team: "Local Party",
    date: "2025-01-14",
    tactic: "Phone",
    attempts: 15,
    contacts: 8,
    notHome: 6,
    refusal: 1,
    badData: 0,
    support: 6,
    oppose: 2,
    undecided: 0
  },
  {
    firstName: "Chris",
    lastName: "Brown",
    team: "Local Party",
    date: "2025-01-14",
    tactic: "SMS",
    attempts: 8,
    contacts: 1,
    notHome: 6,
    refusal: 0,
    badData: 1,
    support: 0,
    oppose: 1,
    undecided: 0
  },
  {
    firstName: "John",
    lastName: "Smith",
    team: "Local Party",
    date: "2025-01-15",
    tactic: "Phone",
    attempts: 15,
    contacts: 12,
    notHome: 0,
    ref
