// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjrsaozdkbeminvckrvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqcnNhb3pka2JlbWludmNrcnZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODc2OTcsImV4cCI6MjA1NzQ2MzY5N30.CMbRdGByhRjh42vC0-jrt1QHYR0FkpaI1X43Q4o9Yz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);